<a href="https://colab.research.google.com/github/jiyoungsong-pr/prac_class/blob/main/numpy_%EC%A0%95%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

반복문 없이 데이터 배열 처리 빠름 
중요한 기본이 되는 패키지 

In [3]:
import numpy as np
np.__version__

'1.21.5'

In [6]:
a1=np.array([1,2,3,4,5])
print (a1)
print(type(a1))
print(a1.shape )
print(a1[0],a1[1],a1[2],a1[3],a1[4])
a1[0]=4
a1[1]=5
a1[2]=6
print(a1)
#1차원


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [8]:
#2차원
a2=np.array([[1,2,3],[4,5,6,],[7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0],a2[1,1],a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [10]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],
             [[1,2,3],[4,5,6],[7,8,9]],
             [[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


배열 생성 및 초기화 

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

full(): 모든 요소를 지정한 값으로 초기화 

In [16]:
np.full((3,3),1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

eye(): 단위행렬 생성

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

tri:삼각행렬

In [18]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [19]:
np.empty(10)#초기화 하지 않는 배열 생성

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
print(a1)
np.zeros_like(a1) #shape 같은 모양으로 하나 만들어줘

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [23]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
print(a3)
np.full_like(a3,(3,3))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


ValueError: ignored

arrange():정수범위로 배열 생성 

In [ ]:
np.arrange(0,30,2)

linspace():범위내에서 균등 간격의 배열 

In [25]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

랜덤값 배열 생성 


In [29]:
np.random.random((3,3))

array([[0.77165182, 0.68550192, 0.97718264],
       [0.40796143, 0.38178928, 0.66732088],
       [0.64121729, 0.85756351, 0.98438021]])

In [32]:
np.random.randint(0,10,(3,3))

array([[2, 9, 7],
       [0, 5, 3],
       [9, 9, 0]])

In [33]:
np.random.normal(0,1,(3,3))

array([[ 0.77430927, -0.21506763, -0.42891237],
       [ 0.30249573,  1.12822451, -0.14183068],
       [-1.14400492, -0.54305901, -1.01852999]])

In [35]:
np.random.rand(3,3)

array([[0.52402779, 0.90268237, 0.30822932],
       [0.58987425, 0.45709913, 0.74865024],
       [0.63190648, 0.11165394, 0.02440051]])

In [36]:
np.random.randn(3,3)

array([[ 0.87502224,  1.45005156, -1.1099282 ],
       [-1.44478017,  1.33374552, -0.63604445],
       [ 2.13964685,  1.05171698,  1.36327873]])

표준 데이터 타입 

In [38]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

날짜 시간 배열 

In [45]:
date=np.array('2020-01-01',dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [48]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [49]:
datetime=np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [ ]:
datetime=np.datetime64('2020-06-01 12:0:12.34''ns')
datetime


배열 조회
배열 속성정보


In [51]:
def array_info(array):
  print(array)
  print("ndim:",array.ndim)
  print("shape:",array.shape)
  print("dtype:",array.dtype)
  print("size:",array.size)
  print("itemsize:",array.nbytes)
  print("strides:",array.strides)

In [52]:
array_info(a1)

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 40
strides: (8,)


In [54]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize: 72
strides: (24, 8)


인덱싱(indexing)

In [56]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [58]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


슬라이싱 (slicing)


In [59]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


불리언 인덱싱 (boolean indexing)

In [63]:
print(a1)
bi=[False, True,False,True]
print=(a1[bi])
bi=[True,False,True,True,False]
print(a1[bi])

[4 5 6 4 5]


IndexError: ignored

팬시 인덱싱(fancy indexing)

In [64]:
print(a1)
print([a1[0],a1[2]])
ind=[0,2]
print(a1[ind])
ind = np.array([[0,1],
                [2,0]])
print(a1[ind])

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


배열 값 삽입/삭제 /수정/복사 

In [66]:
print(a1)
b1=np.insert(a1,0,10) #insert 는 값이 변하지 않는다 
print(b1)
print(a1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[4 5 6 4 5]


In [67]:
print(a2)
b2=np.insert(a2,1,10,axis=0)
print(b2)
c2=np.insert(a2,1,10,axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


배열 값 수정

In [69]:
print(a1)
a1[0]=1
a1[1]=2
a1[2]=3
print(a1)
a1[:1]=9
print(a1)
i=np.array([1,3,4])
a1[i]=0
print(a1)
a1[i] += 4 #0인 값들이 4로 바뀐다 

print(a1)

[9 2 3 4 5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]


In [71]:
print(a2)
a2[0,0]=1
a2[1,1]=2
a2[2,2]=3
a2[0]=1 #1번째 행은 1로 바꿈
print(a2)
#slicing
a2[1;,2]=9
print(a2)
row=np.array([0,1])
col=np.array([1,2])
a2[row,col]=0
print(a2)

SyntaxError: ignored

배열 값 삭제 


In [73]:
print(a1)
b1=np.delete(a1,1)
print(b1)
print(a1)

[9 0 3 0 0]
[9 3 0 0]
[9 0 3 0 0]


In [ ]:
print(a2)
b2=np.delete(a2,1,axis=0)
print(b2)
c2=np.delete(a2,1,axis=1)
print(c2)

배열 복사 

In [ ]:
print(a2)
print